#include <windows.h>
#include <stdio.h>
#include <string.h>

/* Regression for Papaya fs path normalization in GetFileAttributes paths as
 * generated by Godot 4.3+ pack detection:
 *   1. "\\?\C:\<name>"   extended-length prefix with drive letter
 *   2. "C:\<name>"       plain drive letter
 * Both must resolve to files relative to the process CWD (the game dir).
 * Returns 0 on success, nonzero with a message otherwise. */

static void build_ext_path(WCHAR* dst, const char* name, int extended) {
    /* prefix: "\\?\C:\" or "C:\" */
    const WCHAR prefix_ext[] = L"\\\\?\\C:\\";
    const WCHAR prefix_plain[] = L"C:\\";
    const WCHAR* pre = extended ? prefix_ext : prefix_plain;
    size_t i = 0, j = 0;
    while (pre[i]) { dst[i] = pre[i]; i++; }              /* copy prefix */
    while (name[j]) { dst[i] = (WCHAR)(unsigned char)name[j]; i++; j++; } /* ANSI name */
    dst[i] = 0;
}

int main(void) {
    const char* fname = "papaya_godot_path_probe.txt";
    HANDLE h = CreateFileA(fname, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, 0, NULL);
    if (h == INVALID_HANDLE_VALUE) { printf("fail: create\n"); return 1; }
    DWORD wrote = 0;
    const char* data = "papaya-probe";
    WriteFile(h, data, (DWORD)strlen(data), &wrote, NULL);
    CloseHandle(h);

    WCHAR path[1024];
    build_ext_path(path, fname, 1);       /* "\\?\C:\fname" */
    if (GetFileAttributesW(path) == INVALID_FILE_ATTRIBUTES) {
        printf("fail: drive-extended resolution\n");
        return 2;
    }
    build_ext_path(path, fname, 0);       /* "C:\fname" */
    if (GetFileAttributesW(path) == INVALID_FILE_ATTRIBUTES) {
        printf("fail: plain drive resolution\n");
        return 3;
    }

    DeleteFileA(fname);
    printf("ok\n");
    return 0;
}