#pragma once

#include "papaya/common/types.hpp"
#include <cstdint>
#include <span>
#include <string>
#include <vector>

namespace papaya::gpu {

// D3D11 (DXBC) -> SPIR-V shader translation — multi-session phase (2026-08-31).
//
// Strategy (the "modern faster way" vs hand-writing a DXVK-scale shader engine):
//   * Stage 1 (THIS module, real now): parse the DXBC container — its header,
//     chunk directory, SHDR/SHEX bytecode, and ISGN/OSGN/RDEF reflection chunks.
//     You cannot translate a shader you cannot parse.
//   * Stage 2 (future): drive an existing compiler library (SPIRV-Cross / DXC /
//     glslang) to turn the D3D11 bytecode into SPIR-V, plus D3D11-state->Vulkan
//     pipeline mapping. Papaya writes the state mapping; it does NOT write a
//     shader compiler.
//
// This file defines the self-contained Stage 1 container parser + the
// reflection model the later stages consume.

enum class ShaderKind { Unknown, Vertex, Pixel, Geometry, Hull, Domain, Compute };

struct DxbcChunk {
    u32 tag{0};               // 'SHDR'/'SHEX'/'ISGN'/...
    u32 offset{0};            // byte offset of the chunk in the container
    u32 size{0};              // chunk size in bytes
    std::vector<u8> data;     // chunk body
};

struct ShaderSignatureParam {
    std::string semantic;
    u32 index{0};
    u32 component_type{0};    // DXGI_FORMAT-ish R32/U32/S32/F32/Float
    u32 mask{0};              // which components are written
    u8 system_value{0};       // D3D_NAME_* (POSITION/COLOR/TEXCOORD...)
    u8 register_index{0};
    u8 register_mask{0};      // read/write mask
};

struct ShaderReflection {
    ShaderSignatureParam inputs;
    ShaderSignatureParam outputs;
};

// Parsed result of a DXBC container.
struct DxbcContainer {
    std::vector<DxbcChunk> chunks;   // ordered as in the file
    std::vector<u32> shader_bytecode;
    std::vector<ShaderSignatureParam> input_signature;
    std::vector<ShaderSignatureParam> output_signature;
    ShaderKind kind{ShaderKind::Unknown};
};

// Parse a raw D3D11 bytecode .cso buffer into a DXBC container.
// Returns false when the buffer is not a valid DXBC container (header magic
// 'DXBC' / version / chunk count disagree) — reported, never crash.
bool dxbc_parse(std::span<const u8> data, DxbcContainer& out);

// ---- Stage 2: SM4/SM5 shader instruction decoder ----------------------------
// Walks the D3D11 shader instruction stream (u32 tokens after the chunk's
// version/header) into a list of instructions, each with its opcode and the
// operand register table. Real, self-contained: no compiler lib needed to
// *decode*. The encoding constants are the real on-disk values, generated from
// wine vkd3d-shader's tpf.c (the field-validated SM4/SM5 parser): instruction
// token = length(24-28) | flags(11-13) | opcode(0-7); operand token = register
// type(12-19), index order(20-21), addressing(22-23/25-26/28-29), extended(31).

// Full SM4/SM5 opcode set (values are the encoded bytes, wine vkd3d numbering,
// which is byte-exact with the D3D10_SB_OPCODE table; keep in sync with
// src/gpu/src/sm4_opcodes.inc generated by scripts/gen_sm4_opcodes.py).
enum class ShaderOpcode : u32 {
    Add = 0x00, And = 0x01, Break = 0x02, Breakc = 0x03, Case = 0x06,
    Continue = 0x07, Continuec = 0x08, Cut = 0x09, Default = 0x0A,
    DerivRtx = 0x0B, DerivRty = 0x0C, Discard = 0x0D, Div = 0x0E, Dp2 = 0x0F,
    Dp3 = 0x10, Dp4 = 0x11, Else = 0x12, Emit = 0x13, EmitThenCut = 0x14,
    EndIf = 0x15, EndLoop = 0x16, EndSwitch = 0x17, Eq = 0x18, Exp = 0x19,
    Frc = 0x1A, FtoI = 0x1B, FtoU = 0x1C, Ge = 0x1D, IAdd = 0x1E, If = 0x1F,
    IEq = 0x20, IGe = 0x21, ILt = 0x22, IMad = 0x23, IMax = 0x24, IMin = 0x25,
    IMul = 0x26, INe = 0x27, INeg = 0x28, IShl = 0x29, IShr = 0x2A, IToF = 0x2B,
    Label = 0x2C, Ld = 0x2D, Ld2dms = 0x2E, Log = 0x2F, Loop = 0x30, Lt = 0x31,
    Mad = 0x32, Min = 0x33, Max = 0x34, ShaderData = 0x35, Mov = 0x36,
    Movc = 0x37, Mul = 0x38, Ne = 0x39, Nop = 0x3A, Not = 0x3B, Or = 0x3C,
    ResInfo = 0x3D, Ret = 0x3E, Retc = 0x3F, RoundNe = 0x40, RoundNi = 0x41,
    RoundPi = 0x42, RoundZ = 0x43, Rsq = 0x44, Sample = 0x45, SampleC = 0x46,
    SampleCLz = 0x47, SampleLod = 0x48, SampleGrad = 0x49, SampleB = 0x4A,
    Sqrt = 0x4B, Switch = 0x4C, SinCos = 0x4D, UDiv = 0x4E, ULt = 0x4F,
    UGe = 0x50, UMul = 0x51, UMax = 0x53, UMin = 0x54, UShr = 0x55, UToF = 0x56,
    Xor = 0x57, DclResource = 0x58, DclConstantBuffer = 0x59, DclSampler = 0x5A,
    DclIndexRange = 0x5B, DclOutputTopology = 0x5C, DclInputPrimitive = 0x5D,
    DclVerticesOut = 0x5E, DclInput = 0x5F, DclInputSgv = 0x60, DclInputSiv = 0x61,
    DclInputPs = 0x62, DclInputPsSgv = 0x63, DclInputPsSiv = 0x64, DclOutput = 0x65,
    DclOutputSgv = 0x66, DclOutputSiv = 0x67, DclTemps = 0x68,
    DclIndexableTemp = 0x69, DclGlobalFlags = 0x6A, Lod = 0x6C, Gather4 = 0x6D,
    SamplePos = 0x6E, SampleInfo = 0x6F, HsDecls = 0x71, HsControlPointPhase = 0x72,
    HsForkPhase = 0x73, HsJoinPhase = 0x74, EmitStream = 0x75, CutStream = 0x76,
    FCall = 0x78, BufInfo = 0x79, DerivRtxCoarse = 0x7A, DerivRtxFine = 0x7B,
    DerivRtyCoarse = 0x7C, DerivRtyFine = 0x7D, Gather4C = 0x7E, Gather4Po = 0x7F,
    Gather4PoC = 0x80, Rcp = 0x81, F32ToF16 = 0x82, F16ToF32 = 0x83,
    CountBits = 0x86, FirstBitHi = 0x87, FirstBitLo = 0x88, FirstBitShi = 0x89,
    Ubfe = 0x8A, Ibfe = 0x8B, Bfi = 0x8C, BfRev = 0x8D, Swapc = 0x8E,
    DclStream = 0x8F, DclFunctionBody = 0x90, DclFunctionTable = 0x91,
    DclInterface = 0x92, DclInputControlPointCount = 0x93,
    DclOutputControlPointCount = 0x94, DclTessellatorDomain = 0x95,
    DclTessellatorPartitioning = 0x96, DclTessellatorOutputPrimitive = 0x97,
    DclHsMaxTessFactor = 0x98, DclHsForkPhaseInstanceCount = 0x99,
    DclHsJoinPhaseInstanceCount = 0x9A, DclThreadGroup = 0x9B, DclUavTyped = 0x9C,
    DclUavRaw = 0x9D, DclUavStructured = 0x9E, DclTgsmRaw = 0x9F,
    DclTgsmStructured = 0xA0, DclResourceRaw = 0xA1, DclResourceStructured = 0xA2,
    LdUavTyped = 0xA3, StoreUavTyped = 0xA4, LdRaw = 0xA5, StoreRaw = 0xA6,
    LdStructured = 0xA7, StoreStructured = 0xA8, AtomicAnd = 0xA9, AtomicOr = 0xAA,
    AtomicXor = 0xAB, AtomicCmpStore = 0xAC, AtomicIAdd = 0xAD, AtomicIMax = 0xAE,
    AtomicIMin = 0xAF, AtomicUMax = 0xB0, AtomicUMin = 0xB1, ImmAtomicAlloc = 0xB2,
    ImmAtomicConsume = 0xB3, ImmAtomicIAdd = 0xB4, ImmAtomicAnd = 0xB5,
    ImmAtomicOr = 0xB6, ImmAtomicXor = 0xB7, ImmAtomicExch = 0xB8,
    ImmAtomicCmpExch = 0xB9, ImmAtomicIMax = 0xBA, ImmAtomicIMin = 0xBB,
    ImmAtomicUMax = 0xBC, ImmAtomicUMin = 0xBD, Sync = 0xBE, DAdd = 0xBF,
    DMax = 0xC0, DMin = 0xC1, DMul = 0xC2, DEq = 0xC3, DGe = 0xC4, DLt = 0xC5,
    DNe = 0xC6, DMov = 0xC7, DMovc = 0xC8, DToF = 0xC9, FToD = 0xCA,
    EvalSampleIndex = 0xCC, EvalCentroid = 0xCD, DclGsInstances = 0xCE,
    DDiv = 0xD2, DFma = 0xD3, DRcp = 0xD4, Msad = 0xD5, DToI = 0xD6, DToU = 0xD7,
    IToD = 0xD8, UToD = 0xD9, Gather4S = 0xDB, Gather4CS = 0xDC, Gather4PoS = 0xDD,
    Gather4PoCS = 0xDE, LdS = 0xDF, Ld2dmsS = 0xE0, LdUavTypedS = 0xE1,
    LdRawS = 0xE2, LdStructuredS = 0xE3, SampleLodS = 0xE4, SampleCLzS = 0xE5,
    SampleClS = 0xE6, SampleBClS = 0xE7, SampleGradClS = 0xE8, SampleCClS = 0xE9,
    CheckAccessFullyMapped = 0xEA, Unknown = 0xFFFFFFFFu,
};

// Register type encoded in operand bits 12-19 (D3D10_SB_OPERAND_TYPE).
enum class Sm4RegType : u32 {
    Temp = 0x00, Input = 0x01, Output = 0x02, IndexableTemp = 0x03,
    ImmConst = 0x04, ImmConst64 = 0x05, Sampler = 0x06, Resource = 0x07,
    ConstBuffer = 0x08, ImmConstBuffer = 0x09, PrimId = 0x0B, DepthOut = 0x0C,
    Null = 0x0D, Rasterizer = 0x0E, OMask = 0x0F, Stream = 0x10,
    FunctionBody = 0x11, FunctionPointer = 0x13, OutputControlPointId = 0x16,
    ForkInstanceId = 0x17, JoinInstanceId = 0x18, InputControlPoint = 0x19,
    OutputControlPoint = 0x1A, PatchConstantData = 0x1B, DomainLocation = 0x1C,
    Uav = 0x1E, SharedMemory = 0x1F, ThreadId = 0x20, ThreadGroupId = 0x21,
    LocalThreadId = 0x22, Coverage = 0x23, LocalThreadIndex = 0x24,
    GsInstanceId = 0x25, DepthOutGreaterEqual = 0x26, DepthOutLessEqual = 0x27,
    OutputStencilRef = 0x29, Unknown = 0xFFFFFFFFu,
};

// Relative-addressing index: value = base register + pre-offset.
struct Sm4RelIndex {
    u32 reg_type{0};   // base register class (usually Temp)
    u32 reg_index{0};  // base register number
    u32 offset{0};     // constant offset added to the base (addr == 0x3)
};

// One decoded operand: register class + component selection + indices.
struct DecodedOperand {
    u32 reg_type{0};                // Sm4RegType (bits 12-19)
    u32 dimension{0};               // 0=scalar, 1=2d, 2=3d, 3=vec4 (bits 0-1)
    u32 mask{0};                    // dest write mask, .xyzw bits 0-3 (bits 4-7)
    u32 swizzle{0};                 // src swizzle, 2 bits x 4 components (bits 4-11)
    u32 order{0};                   // number of indexables (bits 20-21)
    u32 extended_type{0};           // extended-operand type (bit 31 present; 0=none)
    u32 modifier{0};                // src modifier: 1=neg, 2=abs, 3=absneg
    std::vector<u32> indices;       // absolute index values (order entries)
    std::vector<Sm4RelIndex> rel;   // relative addressing operands
    std::vector<u32> imm;           // immediate constant words (ImmConst types)
    u32 reg_index() const { return indices.empty() ? 0 : indices[0]; }
};

struct DecodedInstruction {
    ShaderOpcode opcode{ShaderOpcode::Unknown};
    u32 opcode_raw{0};              // raw opcode byte (bits 0-7)
    u32 flags{0};                   // instruction flags (bits 11-13; saturate=0x4)
    u32 length{0};                  // length in u32 tokens incl. the opcode token
    u32 token_offset{0};            // u32 offset of instruction start in stream
    std::vector<u32> modifier_tokens;  // instruction modifiers (AOFFIMMI etc.)
    std::vector<DecodedOperand> operands;
    std::vector<u32> raw_words;     // remaining payload words (DCL semantics,
                                    // counts, resource component types)
};

// Info row for one opcode: encoded value, lowercase asm name, operand arity.
struct Sm4OpcodeInfo {
    u32 opcode{0};
    const char* name{nullptr};
    u8 dst_count{0};
    u8 src_count{0};
};

// Lookup by encoded opcode byte; returns nullptr for opcodes not in the table.
const Sm4OpcodeInfo* sm4_opcode_info(u32 raw_opcode);
// Lowercase assembly name of an opcode ("" for Unknown).
const char* sm4_opcode_name(ShaderOpcode opcode);

// Decode the instruction stream (the u32 words after the shader version, i.e.
// SHDR/SHEX body offset 2). Returns false on malformed input; unknown opcodes
// are decoded structurally (their operands walked via the instruction length)
// and reported as ShaderOpcode::Unknown.
bool sm4_decode(std::span<const u32> stream, std::vector<DecodedInstruction>& out);

// FourCC helper ('SHEX' = 0x58454853 little-endian).
inline u32 fourcc(char a, char b, char c, char d) {
    return static_cast<u32>(a) | (static_cast<u32>(b) << 8) |
           (static_cast<u32>(c) << 16) | (static_cast<u32>(d) << 24);
}

} // namespace papaya::gpu