#!/usr/bin/env python3
"""Generate the per-title compatibility manifest for the installed game corpus.

Methodology (the "don't translate everything" strategy):
  Papaya's edge over Wine/Proton/Box64 is NOT out-reimplementing the Win32 API
  surface. It is selectively native: run each game's OWN engine/runtime without
  reimplementing it, and translate only the small API set that game truly needs.

  For each game under ~/Games this script detects:
    - engine family      (Godot / Godot-Mono / Unity / Java-JVM / SDL / raw Win32)
    - bridge path        (host-native in-process vs host-runtime exec vs JVM)
    - the exe to launch
    - the system DLLs the game imports (via objdump), i.e. the real per-title
      API surface that papaya must service (not the full 13,397-export alphabet)

  Output: docs/game_manifest.md (human) + docs/game_manifest.json (machine) +
          a per-title "top-N DLLs" view so API work is driven by real games.
"""
import json
import subprocess
from pathlib import Path

GAMES = Path.home() / "Games"


def scan_pe_import_root(exe: Path) -> list[str]:
    """DLLs imported by the game (cover small/PCL samples)."""
    out = subprocess.run(["objdump", "-p", str(exe)], capture_output=True, text=True, timeout=20).stdout
    dlls, cur = [], None
    for line in out.splitlines():
        m = __import__("re").match(r"\s*DLL Name:\s*([^\\/]+\.dll)", line, __import__("re").I)
        if m:
            cur = m.group(1).lower()
            if cur not in dlls:
                dlls.append(cur)
    return dlls


def detect_engine(game_dir: Path):
    """Return (engine, bridge_path, pck_or_jar, exe)."""
    exe = None
    for p in sorted(game_dir.rglob("*.exe")):
        low = p.name.lower()
        if "redist" in str(p).lower() or "setup" in low or "crash" in low or "unins" in low or low.startswith("vc_redist"):
            continue
        exe = p
        break
    if not exe:
        return ("unknown", "n/a", "n/a", "?")
    low_dir = str(game_dir).lower()
    has_pck = bool([p for p in game_dir.rglob("*.pck")])
    has_godot_dll = bool([p for p in game_dir.rglob("*.dll") if "godot" in p.name.lower()])
    has_unity = bool([p for p in game_dir.rglob("GameAssembly.dll")])
    has_jar = bool([p for p in game_dir.rglob("*.jar")])
    has_mono = bool([p for p in game_dir.rglob("*") if p.suffix.lower() in (".dll",) and "mono" in p.name.lower()])
    if has_unity:
        return ("unity", "host-native-inprocess", "D3D/IL2CPP", exe.name)
    if has_pck and has_mono:
        return ("godot-mono", "host-native-inprocess(+CLR)", "DLL", exe.name)
    if has_pck or has_godot_dll:
        return ("godot", "host-native-inprocess", "PCK", exe.name)
    if has_jar:
        return ("java-jvm", "engine-bridge(JVM)", "JAR", exe.name)
    return ("raw-win32", "host-native-inprocess", "win32", exe.name)


def main():
    rows = []
    if not GAMES.is_dir():
        print(f"no games dir at {GAMES}")
        return
    for game_dir in sorted(p for p in GAMES.iterdir() if p.is_dir() and p.name != "_CommonRedist"):
        engine, bridge, pack_kind, exe = detect_engine(game_dir)
        exe_path = None
        dlls = []
        if engine != "unknown":
            exe_path = next((p for p in game_dir.rglob("*.exe")
                             if not any(k in p.name.lower() for k in ("redist", "setup", "crash", "unins"))), None)
            if exe_path:
                dlls = scan_pe_import_root(exe_path)
        rows.append({
            "game": game_dir.name,
            "engine": engine,
            "bridge": bridge,
            "pack": pack_kind,
            "exe": exe,
            "top_dlls": sorted(set(dlls)),
        })

    # Decode common CRT/OS pairs into a tally of per-game API need.
    dll_tally = {}
    for r in rows:
        for d in r["top_dlls"]:
            dll_tally[d] = dll_tally.get(d, 0) + 1

    lines = ["# Papaya — Installed-Game Compatibility Manifest",
             "> Auto-generated by `scripts/gen_game_manifest.py`. Drives the",
             "> 'selectively native' strategy: bridge the game's own runtime;",
             "> account only the APIs these actual games import.\n",
             "| Game | Engine | Bridge path | Pack |",
             "|---|---|---|---|"]
    for r in rows:
        lines.append(f"| {r['game']} | {r['engine']} | {r['bridge']} | {r['pack']} |")
    lines.append("\n## System DLLs imported by the installed games (real API need)\n")
    lines.append("| DLL | games importing |")
    lines.append("|---|---|")
    for dll, n in sorted(dll_tally.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {dll} | {n} |")
    (Path("docs") / "game_manifest.md").write_text("\n".join(lines))
    (Path("docs") / "game_manifest.json").write_text(json.dumps(rows, indent=2))
    n_engine = len({r["engine"] for r in rows})
    print(f"Wrote docs/game_manifest.md + .json: {len(rows)} games, "
          f"{n_engine} engine families, {len(dll_tally)} unique DLLs imported")


if __name__ == "__main__":
    main()