#!/usr/bin/env python3
"""Generate benign codegen stubs for Papaya's Win32 HLE, so every export in the
game-facing surface is *present and callable* (imports resolve, GetProcAddress
probes succeed) without hand-writing each. Real implementations always win
(register_stub never overrides register_function).

Methodology (see docs/DESIGN_SURFACE_CODEGEN.md):
  - Enumerate the game-facing export surface from the mingw import libs.
  - Split the un-implemented exports into SAFE_STUB (benign no-op / feature-
    absent, chosen by name heuristics) and SKIP (needs real semantics: GPU,
    COM, rendering, execution-critical — these stay unresolved so failures are
    loud, not silently corrupt).
  - Emit a .cpp that calls register_stub() for every SAFE_STUB export with a
    return-safety-matched benign thunk.

Usage: python3 scripts/gen_thunks.py > src/win32/src/ucrt_codegen_stubs.inc
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HLE = REPO / "src/win32/src/win32_api_hle.cpp"

# Reuse gen_coverage's DLL list + lib_exports.
sys.path.insert(0, str(REPO / "scripts"))
from gen_coverage import DLLS, lib_exports  # noqa: E402

# Return-arg masked stubs defined in win32_api_hle.cpp.
THUNKS = {
    "zero":    "&codegen_stub_zero",
    "null":    "&codegen_stub_null",
    "true":    "&codegen_stub_true",
    "self":    "&codegen_stub_arg0",
    "hresult": "&codegen_stub_hresult_ok",   # S_OK (0x00000000)
    "hresult_fail": "&codegen_stub_hresult_fail",  # E_NOTIMPL
}

# Functions these DLLs export that are safe to no-op-stub. GPU/COM/rendering
# DLLs are excluded entirely (they need real translation).
SAFE_DLLS = {
    "version", "uxtheme", "dwmapi", "winmm", "shlwapi",
    "iphlpapi", "bcrypt", "crypt32", "setupapi",
}


def classify_stub(dll, name):
    """Return a thunk key and reason, or None if this export must NOT be stubbed."""
    if dll not in SAFE_DLLS:
        return None
    low = name.lower()
    # Version/getting an info pointer: return S_OK / TRUE / 0 depending on set.
    if name.startswith("GetFileVersionInfo") or name in ("VerQueryValueA", "VerQueryValueW",
        "GetFileVersionInfoSizeA", "GetFileVersionInfoSizeW", "VerFindFileA", "VerFindFileW",
        "VerInstallFileA", "VerInstallFileW", "VerLanguageNameA", "VerLanguageNameW"):
        return ("zero", "version")
    # uxtheme: no-op everything (themes degrade gracefully).
    if dll == "uxtheme":
        if name.startswith("GetTheme") or name.startswith("IsTheme"):
            return ("zero", "theme-query")
        if name.startswith("SetTheme"):
            return ("hresult", "theme-set-ok")
        return ("hresult", "theme")
    # dwmapi: framed/glass attributes return S_OK (S_OK=0) or E_NOTIMPL.
    if dll == "dwmapi":
        if name.startswith("DwmGet") and "Attribute" in name:
            return ("hresult_fail", "dwm-get")
        if name.startswith("DwmSet") and "Attribute" in name:
            return ("hresult", "dwm-set")
        return ("hresult", "dwm")
    # winmm: timeGetTime etc already done; optional wave/midi helpers -> MMSYSERR.
    if dll == "winmm":
        if name.startswith("Get"):
            return ("zero", "winmm-query")
        return ("zero", "winmm")
    # shlwapi: string/path helpers -> 0 (absent).
    if dll == "shlwapi":
        return ("zero", "shlwapi")
    # iphlpapi: Get*Adaptors etc -> error/net-absent 0.
    if dll == "iphlpapi":
        return ("zero", "iphlpapi")
    # bcrypt/crypt32: feature-absent -> 0/NTSTATUS-style.
    if dll in ("bcrypt", "crypt32"):
        return ("zero", "crypto-absent")
    # setupapi: device/install queries -> error 0.
    if dll == "setupapi":
        return ("zero", "setupapi")
    return ("zero", "default")


def main():
    text = HLE.read_text()
    real_pat = re.compile(r'register_function\(\s*"([^"]+)"\s*,\s*"([^"]+)"')
    real = set()
    for m in real_pat.finditer(text):
        real.add((m.group(1).upper().removesuffix(".DLL").lower(), m.group(2)))

    # Group stub registrations per DLL (deterministic order).
    by_dll = {}
    skipped = 0
    for dll in DLLS:
        for name in sorted(lib_exports(dll)):
            # Filter import-lib section/helper symbols, not real exports.
            if not name or name[0] == '.' or name.startswith('_') or name.endswith('$'):
                continue
            if (dll, name) in real:
                continue
            cls = classify_stub(dll, name)
            if cls is None:
                skipped += 1
                continue
            key, reason = cls
            by_dll.setdefault(dll, []).append((name, key, reason))

    out = []
    out.append("// AUTO-GENERATED by scripts/gen_thunks.py — do not edit by hand.")
    out.append("// Benign codegen attribution stubs so the full game-facing export")
    out.append("// surface is present/callable (imports resolve, GetProcAddress")
    out.append("// probes succeed). Real implementations never overridden.")
    out.append("static void register_codegen_stubs(Win32ApiHle& hle) {")
    total = 0
    for dll in sorted(by_dll):
        out.append(f"    // {dll} ({len(by_dll[dll])})")
        for name, key, reason in by_dll[dll]:
            out.append(f'    hle.register_stub("{dll}.DLL", "{name}", reinterpret_cast<void*>({THUNKS[key]}));')
            total += 1
    out.append("}")
    print("\n".join(out))
    n_skip = skipped
    import sys as _s
    _s.stderr.write(f"generated {total} stubs; skipped {n_skip} (need real semantics)\n")


if __name__ == "__main__":
    main()