#!/usr/bin/env python3
"""Generate src/gpu/src/sm4_opcodes.inc from wine vkd3d-shader's tpf.c.

Source of truth: http://github.com/wine-mirror/wine
  libs/vkd3d/libs/vkd3d-shader/tpf.c  (commit 9226b10cd1d78a0ce8034b1e374493cdd3bab994)
That file is the D3D10/11 "tokenized program format" (SM4/SM5) parser used by
wine's d3d12/vulkan shader path and cross-validated against native fxc output,
so the encoding constants below are the real on-disk values (instruction token:
opcode bits 0-7, flags bits 11-13, length bits 24-28; operand token: register
type bits 12-19, order bits 20-21, addressing bits 22-23/25-26/28-29, extended
operand bit 31).

Regenerate:  python3 scripts/gen_sm4_opcodes.py /path/to/tpf.c > src/gpu/src/sm4_opcodes.inc
"""

import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "/tmp/tpf.c"
text = open(SRC, encoding="utf-8").read()

# --- parse enum vkd3d_sm4_opcode { ... VKD3D_SM4_OP_COUNT }; ---
enum_blob = re.search(r"enum vkd3d_sm4_opcode\s*\{(.*?)\s*VKD3D_SM4_OP_COUNT\s*,?\s*\};", text, re.S).group(1)
opcode_value = {}
for m in re.finditer(r"(VKD3D_SM[45]_OP_[A-Z0-9_]+)\s*=\s*(0x[0-9a-fA-F]+|\d+)", enum_blob):
    opcode_value[m.group(1)] = int(m.group(2), 0)

# --- parse the opcode info table: {OP, HANDLER, "dst", "src", [read_func, [bool]]} ---
table_blob = re.search(r"static const struct vkd3d_sm4_opcode_info opcode_table\[\]\s*=\s*\{(.*?)\n\s*\};", text, re.S).group(1)
entries = []  # (name, value, dst_count, src_count)
for m in re.finditer(r"\{\s*(VKD3D_SM[45]_OP_[A-Z0-9_]+)\s*,\s*\w+\s*,\s*\"([^\"]*)\"\s*,\s*\"([^\"]*)\"", table_blob):
    name, dst, src = m.group(1), m.group(2), m.group(3)
    entries.append((name, opcode_value[name], len(dst), len(src)))

# sanity: every table entry must be in the enum
assert len(entries) == len(opcode_value), f"table {len(entries)} != enum {len(opcode_value)}"

# --- C identifier from vkd3d enum name ("VKD3D_SM4_OP_DCL_INPUT_PS_SGV" -> DclInputPsSgv) ---
def cid(name):
    body = name.replace("VKD3D_SM4_OP_", "").replace("VKD3D_SM5_OP_", "")
    return "".join(p.capitalize() for p in body.split("_"))

def lname(name):
    body = name.replace("VKD3D_SM4_OP_", "").replace("VKD3D_SM5_OP_", "")
    if body == "EMITTHENCUT":
        return "emit_then_cut"
    return body.lower()

# Emit, in enum order (== numeric value order in the table rows)
out = []
out.append("// Generated by scripts/gen_sm4_opcodes.py from wine vkd3d-shader tpf.c\n")
out.append("// (wine-mirror/wine @ 9226b10cd1d78a0ce8034b1e374493cdd3bab994). Do not edit by hand.\n")
out.append("// format: {opcode_value, \"asm_name\", dst_operand_count, src_operand_count}\n")
for name, value, dst, src in entries:
    if value == 0x14:
        raise SystemExit("0x14 already in table")
# SM4.0-only opcode removed from the d3d11-era table but valid in real shaders:
entries.append(("VKD3D_SM4_OP_EMITTHENCUT", 0x14, 0, 0))

out = []
out.append("// Generated by scripts/gen_sm4_opcodes.py from wine vkd3d-shader tpf.c\n")
out.append("// (wine-mirror/wine @ 9226b10cd1d78a0ce8034b1e374493cdd3bab994). Do not edit by hand.\n")
out.append("// format: {opcode_value, \"asm_name\", dst_operand_count, src_operand_count}\n")
for name, value, dst, src in sorted(entries, key=lambda e: e[1]):
    out.append(f"    {{{value:#04x}, \"{lname(name)}\", {dst}, {src}}},  // {cid(name)}")
open("/dev/stdout", "w", encoding="utf-8").write("\n".join(out) + "\n")