#!/usr/bin/env python3
"""Rank the top ~1000 Windows API exports by real-world need for Papaya.

Usage: python3 scripts/gen_top1000.py   (from repo root)

Ranking signal:
  1. Real game/application PE import tables under ~/Games (the actual target
     corpus) and the in-repo mingw guest suite in build/guests. Count how many
     binaries import each (dll, symbol).
  2. DLL priority tier (core CRT/OS first, then graphics/audio).
  3. Emit docs/TOP_1000_APIS.md. Symbols Papaya already implements are marked
     YES; the top rows with no marker are the next real work queue.
"""
import re
import subprocess
from pathlib import Path
from collections import Counter

REPO = Path(__file__).resolve().parent.parent
HLE = REPO / "src/win32/src/win32_api_hle.cpp"
GUESTS = REPO / "build" / "guests"
GAMES = Path.home() / "Games"

CORE = {"kernel32", "msvcrt", "user32", "gdi32", "ntdll", "advapi32",
        "ole32", "oleaut32", "shell32", "shlwapi", "ws2_32", "wsock32",
        "winmm", "version", "setupapi", "imm32", "iphlpapi", "dwmapi",
        "shcore", "comctl32", "comdlg32", "uxtheme", "crypt32", "bcrypt"}
GRAPHICS = {"d3d9", "d3d10", "d3d11", "d3d12", "dxgi", "ddraw", "d2d1",
            "dwrite", "opengl32", "dinput", "dinput8", "dsound", "xaudio2"}


def scan_eifs(paths):
    """Yield (dll, name) for every import member seen across the given PEs."""
    for exe in paths:
        try:
            out = subprocess.run(["objdump", "-p", str(exe)],
                                 capture_output=True, text=True, timeout=30).stdout
        except (subprocess.TimeoutExpired, OSError):
            continue
        cur = None
        for line in out.splitlines():
            m = re.match(r"\s*DLL Name:\s*([^\\/]+\.dll)", line, re.I)
            if m:
                cur = m.group(1).lower().removesuffix(".dll")
                continue
            if cur:
                m = re.match(r"\s*[0-9a-f]+\s+\d+\s+([A-Za-z_@$?][A-Za-z0-9_@$?]*)", line)
                if m:
                    yield (cur, m.group(1))


def imports_weighted() -> dict[tuple[str, str], int]:
    """(dll, name) -> count of distinct binaries (real games weighted x4)."""
    count: Counter = Counter()
    paths = []
    if GUESTS.is_dir():
        paths += list(GUESTS.glob("*.exe"))
    game_bins = []
    if GAMES.is_dir():
        for exe in GAMES.rglob("*.exe"):
            # Skip common runtime/redist installers that skew the ranking.
            low = exe.name.lower()
            if "redist" in str(exe).lower() or "setup" in low or "unins" in low \
               or "crashpad" in low or low.startswith("vc_redist"):
                continue
            game_bins.append(exe)
    for dll, name in scan_eifs(paths):
        count[(dll, name)] += 1
    for dll, name in scan_eifs(game_bins):
        count[(dll, name)] += 4  # real game import is a strong signal
    return dict(count)


def hle_implemented() -> set[tuple[str, str]]:
    text = HLE.read_text()
    pat = re.compile(r'register_function\(\s*"([^"]+)"\s*,\s*"([^"]+)"')
    out = set()
    for m in pat.finditer(text):
        dll = m.group(1).upper().removesuffix(".DLL").lower()
        out.add((dll, m.group(2)))
    return out


def main():
    impl = hle_implemented()
    usage = imports_weighted()
    rows = []
    for (dll, name), n in usage.items():
        tier = 0 if dll in CORE else (1 if dll in GRAPHICS else 2)
        rows.append((dll, name, n, tier, (dll, name) in impl))
    # sort: usage desc, tier asc, unimplemented first, dll, name
    rows.sort(key=lambda r: (-r[2], r[3], r[4], r[0], r[1]))

    lines = []
    lines.append("# Papaya — Top 1000 APIs by real-world import usage\n")
    lines.append("> Auto-generated by `scripts/gen_top1000.py` — do not edit by hand.\n")
    lines.append("Ranking: number of binaries importing the symbol from real "
                 "game executables under `~/Games` (weight x4) and the in-repo "
                 "`build/guests` mingw suite, then DLL core-tier, then "
                 "unimplemented-first. Empty `implemented` = next work queue.\n")
    lines.append("| # | DLL | Export | binaries importing | tier | implemented |")
    lines.append("|---:|---|---|---:|---:|---|")
    for i, (dll, name, n, tier, is_impl) in enumerate(rows[:1000], 1):
        lines.append(f"| {i} | {dll}.dll | {name} | {n} | {tier} | {'YES' if is_impl else ''} |")
    lines.append("")
    printed = len(rows[:1000])
    unimplemented = sum(1 for r in rows[:1000] if not r[4])
    lines.append(f"Unique (dll, symbol) imports observed: {len(usage)}; top "
                 f"{printed} shown; {unimplemented} of those not yet implemented.")
    (REPO / "docs" / "TOP_1000_APIS.md").write_text("\n".join(lines))
    print(f"Wrote docs/TOP_1000_APIS.md: {printed} rows from {len(usage)} unique "
          f"imports, {sum(1 for r in rows if r[4])} implemented, "
          f"{unimplemented} unimplemented in top 1000")


if __name__ == "__main__":
    main()