#!/usr/bin/env python3
"""Rank the top ~1000 Windows API exports by real-world need for Papaya.

Usage: python3 scripts/gen_top1000.py   (from repo root)

Ranking proxy:
  1. Count how many guest test executables in /tmp/pvx/*.exe import each
     symbol (objdump -p import table) — real usage from the actual corpus.
  2. Add a DLL priority tier (core CRT/OS DLLs first, then graphics/audio).
  3. Emit docs/TOP_1000_APIS.md with the top 1000 unimplemented+implemented
     exports, so the next HLE families are chosen by evidence, not alphabet.
"""
import re
import subprocess
from pathlib import Path
from collections import Counter

REPO = Path(__file__).resolve().parent.parent
HLE = REPO / "src/win32/src/win32_api_hle.cpp"
GUESTS = Path("/tmp/pvx")

CORE = {"kernel32", "msvcrt", "user32", "gdi32", "ntdll", "advapi32",
        "ole32", "oleaut32", "shell32", "shlwapi", "ws2_32", "wsock32",
        "winmm", "version", "setupapi", "imm32"}
GRAPHICS = {"d3d9", "d3d10", "d3d11", "d3d12", "dxgi", "ddraw", "d2d1",
            "dwrite", "opengl32", "dinput", "dinput8", "dsound", "xaudio2"}


def guest_imports() -> dict[tuple[str, str], int]:
    """(dll, name) -> number of guest exes importing it."""
    count: Counter = Counter()
    if not GUESTS.is_dir():
        return {}
    for exe in GUESTS.glob("*.exe"):
        out = subprocess.run(["objdump", "-p", str(exe)],
                             capture_output=True, text=True).stdout
        cur = None
        for line in out.splitlines():
            m = re.match(r"\s*DLL Name:\s*([^\\/]+\.dll)", line, re.I)
            if m:
                cur = m.group(1).lower()
                continue
            if cur:
                m = re.match(r"\s*[0-9a-f]+\s+\d+\s+([A-Za-z_@$?][A-Za-z0-9_@$?]*)", line)
                if m:
                    count[(cur.removesuffix(".dll"), m.group(1))] += 1
    return count


def hle_implemented() -> set[tuple[str, str]]:
    text = HLE.read_text()
    pat = re.compile(r'register_function\(\s*"([^"]+)"\s*,\s*"([^"]+)"')
    out = set()
    for m in pat.finditer(text):
        dll = m.group(1).upper().removesuffix(".DLL").lower()
        out.add((dll, m.group(2)))
    return out


def main():
    impl = hle_implemented()
    usage = guest_imports()
    rows = []
    for (dll, name), n in usage.items():
        tier = 0 if dll in CORE else (1 if dll in GRAPHICS else 2)
        rows.append((dll, name, n, tier, (dll, name) in impl))
    # sort: usage desc, tier asc, dll, name
    rows.sort(key=lambda r: (-r[2], r[3], r[0], r[1]))

    lines = []
    lines.append("# Papaya — Top 1000 APIs by real-world import usage\n")
    lines.append("> Auto-generated by `scripts/gen_top1000.py` — do not edit by hand.\n")
    lines.append("Ranking = number of guest test executables in `/tmp/pvx` that "
                 "import the symbol (real usage), then DLL core-tier, then name.\n")
    lines.append("| # | DLL | Export | guests importing | tier | implemented |")
    lines.append("|---:|---|---|---:|---:|---|")
    for i, (dll, name, n, tier, is_impl) in enumerate(rows[:1000], 1):
        lines.append(f"| {i} | {dll}.dll | {name} | {n} | {tier} | {'YES' if is_impl else ''} |")
    lines.append("")
    printed = len(rows[:1000])
    lines.append(f"Total guest imports observed: {len(usage)} unique "
                 f"(dll, symbol) pairs; top {printed} shown.")
    (REPO / "docs" / "TOP_1000_APIS.md").write_text("\n".join(lines))
    print(f"Wrote docs/TOP_1000_APIS.md: {printed} rows from {len(usage)} "
          f"unique imports, {sum(1 for r in rows if r[4])} already implemented")


if __name__ == "__main__":
    main()