#!/usr/bin/env python3
"""Regenerate docs/GAME_API_COVERAGE.md from the real mingw-w64 import libs
and Papaya's HLE register_function table.

Usage: python3 scripts/gen_coverage.py   (from repo root)

Data sources:
  - per-DLL export totals:  x86_64-w64-mingw32-nm --defined-only on
    /usr/x86_64-w64-mingw32/lib/lib<dll>.a
  - Papaya implemented set: register_function("DLL", "Name", ...) calls in
    src/win32/src/win32_api_hle.cpp (dll names uppercased internally).
"""
import re
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HLE = REPO / "src/win32/src/win32_api_hle.cpp"
LIBDIR = Path("/usr/x86_64-w64-mingw32/lib")
NM = "x86_64-w64-mingw32-nm"

# Same 37 game-facing DLLs as the original catalog.
DLLS = [
    "advapi32", "bcrypt", "comdlg32", "crypt32", "d2d1", "d3d11", "d3d12",
    "d3d9", "dcomp", "ddraw", "dinput", "dinput8", "dsound", "dwmapi",
    "dwrite", "dxgi", "gdi32", "imm32", "iphlpapi", "kernel32", "msvcrt",
    "ntdll", "ole32", "oleaut32", "opengl32", "setupapi", "shell32",
    "shlwapi", "user32", "uxtheme", "version", "winmm", "ws2_32",
    "wsock32", "xinput1_3", "xinput1_4", "xinput9_1_0",
]


def lib_exports(dll: str) -> set[str]:
    """Exported symbol names of a mingw import lib (game-visible surface)."""
    lib = LIBDIR / f"lib{dll}.a"
    if not lib.exists():
        return set()
    out = subprocess.run([NM, "--defined-only", str(lib)],
                         capture_output=True, text=True).stdout
    syms = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        name = parts[2]
        # import libs expose __imp_<name> for data, plus the plain name.
        if name.startswith("__imp_") or name.startswith("____imp_"):
            continue
        # strip leading underscore only for the x86 stdcall decoration noise
        syms.add(name)
    return syms


def hle_implemented() -> dict[str, set[str]]:
    """dll -> set(export names) from register_function calls."""
    text = HLE.read_text()
    table: dict[str, set[str]] = {}
    # register_function("DLL.dll", "Name", ...) — dll names uppercased internally
    pat = re.compile(r'register_function\(\s*"([^"]+)"\s*,\s*"([^"]+)"')
    for m in pat.finditer(text):
        dll = m.group(1).upper()
        # register_function("MSVCRT.DLL", ...) style already uppercased; strip "DLL"
        dll = dll.removesuffix(".DLL")
        table.setdefault(dll.lower(), set()).add(m.group(2))
    return table


def hle_surface() -> dict[str, dict[str, str]]:
    """dll -> {export: severity} where severity is 'real' (register_function)
    or 'stub' (register_stub codegen). Reads the HLE file + the generated
    codegen stub include."""
    surface: dict[str, dict[str, str]] = {}
    text = HLE.read_text()
    pat = re.compile(r'(register_function|register_stub)\(\s*"([^"]+)"\s*,\s*"([^"]+)"')
    for m in pat.finditer(text):
        kind = "real" if m.group(1) == "register_function" else "stub"
        dll = m.group(2).upper().removesuffix(".DLL").lower()
        surface.setdefault(dll, {}).setdefault(m.group(3), kind)
    # Generated include registers the bulk of stubs.
    inc = HLE.parent / "gen_codegen_stubs.inc"
    if inc.exists():
        for m in re.finditer(r'register_stub\(\s*"([^"]+)"\s*,\s*"([^"]+)"', inc.read_text()):
            dll = m.group(1).upper().removesuffix(".DLL").lower()
            surface.setdefault(dll, {}).setdefault(m.group(2), "stub")
    return surface


def main():
    surface = hle_surface()
    rows = []
    total_all = impl_all = stub_all = 0
    for dll in DLLS:
        exports = lib_exports(dll)
        got_map = surface.get(dll, {})
        real = {n for n, k in got_map.items() if k == "real"} & exports
        stub = {n for n, k in got_map.items() if k == "stub"} & exports
        callable = real | stub
        total_all += len(exports)
        impl_all += len(real)
        stub_all += len(stub)
        pct = (100.0 * len(real) / len(exports)) if exports else 0.0
        call_pct = (100.0 * len(callable) / len(exports)) if exports else 0.0
        status = ("NONE" if not real else
                  "LOW" if pct < 20 else
                  "PARTIAL" if pct < 80 else "COVERED")
        rows.append((dll, len(exports), len(real), len(stub), len(callable), pct, call_pct, status))

    rows.sort(key=lambda r: (r[0]))
    overall = (100.0 * impl_all / total_all) if total_all else 0.0
    overall_call = (100.0 * (impl_all + stub_all) / total_all) if total_all else 0.0

    lines = []
    lines.append("# Papaya — Game API Coverage Catalog\n")
    lines.append("> Auto-generated by `scripts/gen_coverage.py` — do not edit by hand.\n")
    lines.append("Generated from the real mingw-w64 import libraries on this host "
                 "(37 game-facing DLLs), cross-referenced against Papaya's Win32 HLE "
                 "`register_function` (real) and codegen `register_stub` (benign "
                 "attribution stub) tables.\n")
    lines.append("## Coverage summary (real, data-driven)\n")
    lines.append("| DLL | total | real | stub | callable | implemented% | callable% | status |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---|")
    for dll, total, real, stub, callable, pct, call_pct, status in rows:
        lines.append(f"| {dll}.dll | {total} | {real} | {stub} | {callable} | {pct:.0f}% | {call_pct:.0f}% | {status} |")
    lines.append(f"| **TOTAL** | **{total_all}** | **{impl_all}** | **{stub_all}** | "
                 f"**{impl_all+stub_all}** | **{overall:.0f}%** | **{overall_call:.0f}%** | |\n")
    lines.append("## Notes\n")
    lines.append("- **real** = `register_function` (genuine HLE implementation).")
    lines.append("- **stub** = `register_stub` from `scripts/gen_thunks.py` — benign, "
                 "call-time-present attribution stubs that make imports resolve and "
                 "`GetProcAddress` probes succeed without claiming real semantics. "
                 "Real implementations are never overridden.")
    lines.append("- **callable** = real+stub, i.e. how many exports resolve at load.")
    lines.append("- Status (real only): NONE, LOW (<20%), PARTIAL (20-79%), COVERED (>=80%).")
    lines.append(f"- Generated {Path(__file__).name} on 2026-08-30; HLE file "
                 f"`{HLE.name}` at {len(surface)} DLL families.\n")
    (REPO / "docs" / "GAME_API_COVERAGE.md").write_text("\n".join(lines))
    print(f"Wrote docs/GAME_API_COVERAGE.md: {total_all} exports, {impl_all} real "
          f"({overall:.1f}%), {impl_all+stub_all} callable ({overall_call:.1f}%) of "
          f"{stub_all} stubbed")


if __name__ == "__main__":
    main()